package bot.estado;

public enum EstadoConversacionBot {
    INICIO,
    MENU_PRINCIPAL,
    REGISTRO_NOMBRE,
    REGISTRO_TELEFONO,
    REGISTRO_DIRECCION,
    REGISTRO_ZONA,
    CONSULTA_PEDIDO_CODIGO,
    CREAR_PEDIDO_SELECCION_COMERCIO,
    CREAR_PEDIDO_SELECCION_PRODUCTO,
    CREAR_PEDIDO_CANTIDAD,
    CREAR_PEDIDO_CONFIRMACION
}
